version: 2

project_name: hyperx

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: hyperx
    main: ./cmd/hyperx/main.go
    binary: hyperx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: SeaBassLab
    name: hyperx
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser)
